<?php

declare(strict_types=1);

use App\Entity\Document;
use App\Entity\Contract;
use App\Entity\Application;
use App\Entity\Department;
use App\Entity\Employee;
use App\Entity\EmployeeJourneyEntry;
use App\Entity\CareerPath;
use App\Entity\JobFamily;
use App\Entity\Grade;
use App\Entity\JobRole;
use App\Entity\JobOffer;
use App\Entity\LeaveRequest;
use App\Entity\Position;
use App\Entity\Profile;
use App\Entity\RecruitmentRequest;
use App\Entity\EmployeeSkill;
use App\Entity\JobRoleRequiredSkill;
use App\Entity\Skill;
use App\Entity\SkillCategory;
use App\Entity\TrainingRequest;
use App\Entity\TrainingSession;
use App\Entity\TrainingEnrollment;
use App\Entity\OnboardingProcess;
use App\Entity\OnboardingTask;
use App\Entity\EvaluationCycle;
use App\Entity\PerformanceReview;
use App\Entity\Objective;
use App\Entity\TrainingCatalog;
use App\Entity\JobRoleRequiredTraining;
use App\Entity\CareerPlan;
use App\Entity\MobilityRequest;
use App\Entity\CompensationHistory;
use App\Entity\Benefit;
use App\Entity\EmployeeBenefit;
use App\Entity\ExitProcess;
use App\Entity\ExitTask;
use App\Entity\SuccessionPlan;
use App\Entity\SanctionScale;
use App\Entity\DisciplinaryCase;
use App\Entity\User;
use App\Entity\WorkExperience;
use App\Model\Ressource;


return static function (): iterable {

    yield Ressource::new("user", User::class, "US", true);
    yield Ressource::new("profile", Profile::class, "PR", true);
    yield Ressource::new("employee", Employee::class, "EM", true);
    yield Ressource::new("employee_journey_entry", EmployeeJourneyEntry::class, "EJ", true);
    yield Ressource::new("work_experience", WorkExperience::class, "WE", true);
    yield Ressource::new("job_role_required_skill", JobRoleRequiredSkill::class, "JRS", true);
    yield Ressource::new("skill_category", SkillCategory::class, "SKC", true);
    yield Ressource::new("skill", Skill::class, "SK", true);
    yield Ressource::new("employee_skill", EmployeeSkill::class, "ES", true);
    yield Ressource::new("document", Document::class, "DC", true);
    yield Ressource::new("department", Department::class, "DP", true);
    yield Ressource::new("job_family", JobFamily::class, "JF", true);
    yield Ressource::new("grade", Grade::class, "GR", true);
    yield Ressource::new("job_role", JobRole::class, "JR", true);
    yield Ressource::new("career_path", CareerPath::class, "CP", true);
    yield Ressource::new("contract", Contract::class, "CT", true);
    yield Ressource::new("leave_request", LeaveRequest::class, "LR", true);
    yield Ressource::new("position", Position::class, "PO", true);
    yield Ressource::new("recruitment_request", RecruitmentRequest::class, "RR", true);
    yield Ressource::new("job_offer", JobOffer::class, "JO", true);
    yield Ressource::new("application", Application::class, "AP", true);
    yield Ressource::new("training_request", TrainingRequest::class, "TR", true);
    yield Ressource::new("training_session", TrainingSession::class, "TS", true);
    yield Ressource::new("training_enrollment", TrainingEnrollment::class, "TE", true);
    yield Ressource::new("onboarding_process", OnboardingProcess::class, "OP", true);
    yield Ressource::new("onboarding_task", OnboardingTask::class, "OT", true);
    yield Ressource::new("evaluation_cycle", EvaluationCycle::class, "EC", true);
    yield Ressource::new("performance_review", PerformanceReview::class, "PV", true);
    yield Ressource::new("objective", Objective::class, "OB", true);
    yield Ressource::new("training_catalog", TrainingCatalog::class, "TC", true);
    yield Ressource::new("job_role_required_training", JobRoleRequiredTraining::class, "JRT", true);
    yield Ressource::new("career_plan", CareerPlan::class, "PL", true);
    yield Ressource::new("mobility_request", MobilityRequest::class, "MB", true);
    yield Ressource::new("compensation_history", CompensationHistory::class, "CH", true);
    yield Ressource::new("benefit", Benefit::class, "BF", true);
    yield Ressource::new("employee_benefit", EmployeeBenefit::class, "EB", true);
    yield Ressource::new("exit_process", ExitProcess::class, "EP", true);
    yield Ressource::new("exit_task", ExitTask::class, "XT", true);
    yield Ressource::new("succession_plan", SuccessionPlan::class, "SP", true);
    yield Ressource::new("sanction_scale", SanctionScale::class, "SS", true);
    yield Ressource::new("disciplinary_case", DisciplinaryCase::class, "DS", true);

};
